export const UPDATE_STEP = 'updateStep'
export const ANIMATION_START = 'animationStart'
export const ANIMATION_END = 'animationEnd'
export const RESET_STEPS = 'resetSteps'
export const CHECK_ACTIVE_ANIMATIONS = 'checkActiveAnimations'